#! /bin/sh
# /etc/init.d/pocsvc

### BEGIN INIT INFO
# Provides:          pocsvc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts proof-of-concept kinesis writer as a service.
# Description:       Starts proof-of-concept kinesis writer as a service.
### END INIT INFO

case "$1" in
  start)
    echo "Starting pocsvc"
    /usr/bin/mono-service -l:/home/nick/kinesis/svc/service.lock -d:/home/nick/kinesis/svc /home/nick/kinesis/svc/PocUnifiledLogService.exe
    ;;
  stop)
    echo "Stopping awskinesissvc"
    killall mono
    ;;
  *)
    echo "Usage: /etc/init.d/pocsvc {start|stop}"
    exit 1
    ;;
esac

exit 0 