#! /bin/sh
# /etc/init.d/kinesiswriter

### BEGIN INIT INFO
# Provides:          kinesiswriter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       Simple script to start a program at boot
### END INIT INFO

case "$1" in
  start)
    echo "Starting kinesiswriter"
    /usr/bin/mono-service2 /home/nick/kinesis/PocUnifiedLogWorker.exe
    ;;
  stop)
    echo "Stopping kinesiswriter"
    killall mono-service2
    ;;
  *)
    echo "Usage: /etc/init.d/kinesiswriter {start|stop}"
    exit 1
    ;;
esac

exit 0 
